name: Release Deliver to Master

on:
  release:
    types: [published]

jobs:
  publish_docs:
    name: "Publish the the Release to Master"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout master
        uses: actions/checkout@v2.4.0
      - name: Merge Tag -> Master
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: {{"${{"}} github.event.ref {{"}}"}}
          target_branch: {{ cookiecutter.gh_latest_branch }}
          github_token: {{"${{"}} github.token {{"}}"}}
