---
# These settings are synced to GitHub by https://probot.github.io/apps/settings/

_extends: {{cookiecutter.plumbing_repo}}:.github/commons-settings.yml

repository:
  name: {{cookiecutter.__name}}
  description: {{cookiecutter.description}}
  homepage: {{cookiecutter.__homepage}}
  topics: {{cookiecutter.topics}}
